ZSH_THEME_NVM_PROMPT_PREFIX="ndoe:"
ZSH_THEME_NVM_PROMPT_SUFFIX=""

ZSH_THEME_GIT_PROMPT_PREFIX="|"
ZSH_THEME_GIT_PROMPT_SUFFIX=""
ZSH_THEME_GIT_PROMPT_DIRTY="|💩"
ZSH_THEME_GIT_PROMPT_CLEAN="|⭐️"

PROMPT=$'╭ %2~ git:[$(git_repo_name)$(git_prompt_info)]\n╰→ '